# Generated by Django 5.2.6 on 2025-09-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('email_sender', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
