# Generated by Django 5.2.6 on 2025-09-17 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_issues', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(db_column='open', default=0)),
                ('closed_issues', models.IntegerField(db_column='closed', default=0)),
                ('by_priority_json', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.project')),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
